sudo: false
language: php
php:
- 7.0
- 7.1
before_script:
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install
script: vendor/bin/phpunit tests
env:
  - SH=bash
deploy:
  provider: heroku
  api_key:
    secure: qxCbcUPuL6yTwXfmh3mfU2zNoDfzvKNPC1OxOEPOjpve6y2qOzPFn5gaQFZnXggXdHST6G2iYdi/HkH2fca0vCXDaZ0/RdS1FflQgK9sFrhq+B1DSwZjXV71ONHt2Lkk4FheEW9W4QOhQwlp2jW0nmeSL38cFSmOhfiYmFLfZiitjdlAWQcXgKvFG6aZYfHpTg+4oafDX7KiaDwBl2kAaECEDKyzjw3XjfKn1t/ovnGNZdBSqcpunar546YGNuuS1G+dYp3Z+zDbXXkGdbgfHI4UVXKwwDxNU23jkGJyoFBbWStyoVTfQrNYOiRFjlytTXXrIFPLEb7vhYpGb+3SHpTRrHMfk2WpJMNBnuhQ4q0ir4XGYmdpq6zxsNMB+hDRFUjp/Niu/9sVL83AcbvyX4k4RFzq9efRsj6XMaGJ/IjhO0y3MOWTkmUVFu/qEWetrE4RCZHjaEA0dHH2MxF/OvIjhytVCeXyUvCHuHM52462qoDVACyC+3Ft8/UMn7uhQKAlbxaUcOwPlS0B1b7HQbLv2D7XxZl9fL6vSqcoJ5VaODArMafZFn6GOUNOdZlM9FLJd6WO4ayuhHacnRKkMkxbAkPmnc7nbLgxKmDAhMuuM2UXYT6cBVR3xM8MrPnxcg+eWP27zKiLThTlPDQ4m69cH5xFsL8ex/+h7d9u248=
  app: startboots-mx
  on:
    repo: lugoff23/startboots-mx
